name: Docker Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - docker example
    runs-on: ubuntu-latest
    container: grafana/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run smoke browser test
        run: |
          export K6_BROWSER_HEADLESS=true
          export K6_WEB_DASHBOARD=true
          export K6_WEB_DASHBOARD_EXPORT=test-results/performance-html-report-smoke.html
          export K6_BROWSER_ARGS='no-sandbox'
          mkdir -p test-results 
          if [ "$ACT" = "true" ]; then
            export K6_BROWSER_EXECUTABLE_PATH=/usr/bin/google-chrome
          fi
          export SCENARIO=smoke
          k6 run performance/performance.js
          ls -l test-results
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          path: test-results/performance-html-report-*.html
        if: always()