name: k6 Performance Test

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: macos-latest # Use macos-latest for browser support

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/k6-action@v0.2.0 # Use the latest version
        with:
          version: latest

      - name: Run k6 browser test
        run: k6 run performance/performance-test.js # Replace with your script name

      - name: Check k6 thresholds (Optional)
        run: k6 check performance/performance-test.js