name: k6 Performance Test

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install k6
        uses: actions/setup-node@v3
        with:
          node-version: 16 # or a suitable version
      - run: npm install -g k6@latest # or a specific k6 version (e.g., k6@0.47.0)

      - name: Run k6 browser test
        run: npx k6 run performance/performance-test.js

      - name: Check k6 thresholds (Optional)
        run: npx k6 check performance/performance-test.js